name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag haiku-for-codespaces:${{ github.sha }}
    
    - name: Azure CIS container scan
      uses: Azure/container-scan@v0.1
      with:
        image-name: haiku-for-codespaces:${{ github.sha }}

    # You may pin to the exact commit or the version.
    # uses: snyk/actions@7fad562681122205233d1242c3bb39598c5393da
    # - uses: snyk/actions@0.3.0
    #   name: Snyk
    #   with:
    #     # Which Snyk command to run, defaults to test
    #     command: test # optional, default is test
    #     # Additional arguments to pass to Snyk
